#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=24G
#SBATCH --time=23:00:00
#SBATCH --partition=amilan
#SBATCH --error=job_outs/twist_coverage-%j.err  
#SBATCH --output=job_outs/twist_coverage-%j.out
#SBATCH --qos normal

### Source config to get paths
. config_loose.sh # Using $project, $pipeoutdir
project_dir_of_bams=${pipeoutdir}/preprocessing/recalibrated/

### Other paths
calc_cov_dir=${project}/twist_coverage/
BED1=${project}/"Probes_merged_ok_CU-Hayashi_PedSolidTumorTransloc_TE-92680772_hg38_250404204242.bed"    # your regions of interest

### Autogenerated paths
GENOME1=${calc_cov_dir}/"genome_temp.txt"
OUTSIDE_BED1=${calc_cov_dir}/"outside_regions_temp.bed"
RESULTS=${calc_cov_dir}/"summary_results.txt"
BED=${calc_cov_dir}/"sorted.bed"
GENOME=${calc_cov_dir}/"genome.txt"
OUTSIDE_BED=${calc_cov_dir}/"outside_regions.bed" 

# Load modules
module load bedtools/2.29.1
module load samtools

# Create and enter directory
mkdir ${calc_cov_dir}
cd ${calc_cov_dir}

# Get sample directories
samples=( $(ls -d ${project_dir_of_bams}/*/) )

# Get genome info from the first BAM file (all BAMs assumed same reference)
#first_bam=$(ls *.bam | head -n 1)
first_bam_path="${samples[0]}"
first_bam_base=$(basename ${samples[0]})
first_bam="${first_bam_path}"/"${first_bam_base}".recal.bam
echo ${first_bam}

# Generate genome file for bedtools complement
samtools view -H $first_bam | grep "@SQ" | sed 's/@SQ\tSN://' | sed 's/\tLN:/\t/' > $GENOME1

# Make sure all bed files have the same sort as bam (need the 'V')
sort -k1,1V -k2,2n -k3,3n $GENOME1 > $GENOME
sort -k1,1V -k2,2n -k3,3n $BED1 > $BED

# Compute complement regions (outside of BED)
bedtools complement -i $BED -g $GENOME > $OUTSIDE_BED1
sort -k1,1V -k2,2n -k3,3n $OUTSIDE_BED1 > $OUTSIDE_BED

# Header for results file
#echo -e "Sample\tMedianInside\tPct10XInside\tMedianOutside\tPct10XOutside" > $RESULTS
echo -e "Sample\tInsideBases\tMedianInside\tPctAt10XInside\tPctAt200XInside\tOutsideBases\tMedianOutside\tPctAt10XOutside\tPctAt200XOutside" > $RESULTS

# Loop through each sample                                                                                                                                                                                      
for sample_dir in ${samples[@]}; do

    # Get basename
    sample=$(basename "$sample_dir")
    echo "Processing sample: $sample"

    prefix=${sample}
    bam="${sample_dir}/${sample}.recal.bam"

    echo "BED file: $BED"
    echo "BAM file: $bam"


    ## Inside statistics
    
    # Coverage inside BED regions (histogram-based, includes zeros because target regions are covered in BAM)
    bedtools coverage -a $BED -b $bam -hist -sorted -g $GENOME > ${prefix}_inside_cov.txt

    # Statistics
    bases_inside=$(awk '$1 != "all" {sum += $6} END {print sum}' ${prefix}_inside_cov.txt)
    median_inside=$(awk '$1 != "all" {for(i=0;i<$6;i++) print $5}' ${prefix}_inside_cov.txt | sort -n | awk '{a[NR]=$1} END {print (NR%2==1)?a[(NR+1)/2]:(a[NR/2]+a[NR/2+1])/2}')
    pct10_inside=$(awk '$1 != "all" {if ($5 > 10) high += $6; total += $6} END {print high/total*100}' ${prefix}_inside_cov.txt)
    pct200_inside=$(awk '$1 != "all" {if ($5 > 200) high += $6; total += $6} END {print high/total*100}' ${prefix}_inside_cov.txt)


    ## Outside statistics
    
    # Coverage outside BED regions (using genomecov to include true zero-coverage regions)
    # Genome-wide coverage including zero-coverage regions
    bedtools genomecov -ibam $bam -bga -g $GENOME > ${prefix}_genomecov.bed

    # Extract coverage in OUTSIDE_BED regions only
    bedtools intersect -a ${prefix}_genomecov.bed -b $OUTSIDE_BED > ${prefix}_outside_cov.bed

    # Statistics
    bases_outside=$(awk '{sum += $3 - $2} END {print sum}' ${prefix}_outside_cov.bed)
    median_outside=$(awk '{
    len = $3 - $2
    count[$4] += len
    total += len
}
END {
    n = int((total + 1) / 2)
    cum = 0
    for (c in count) covs[i++] = c
    nvals = asort(covs)
    for (j = 1; j <= nvals; j++) {
        cov = covs[j]
        cum += count[cov]
        if (cum >= n) {
            print cov
            break
        }
    }
}' ${prefix}_outside_cov.bed )
    pct10_outside=$(awk '{if ($4 > 10) high += $3 - $2; total += $3 - $2} END {print high/total*100}' ${prefix}_outside_cov.bed)
    pct200_outside=$(awk '{if ($4 > 200) high += $3 - $2; total += $3 - $2} END {print high/total*100}' ${prefix}_outside_cov.bed)
			      
    ## Write to summary file
    #echo -e "${prefix}\t$median_inside\t$pct10_inside\t$median_outside\t$pct10_outside" >> $RESULTS
    echo -e "${prefix}\t$bases_inside\t$median_inside\t$pct10_inside\t$pct200_inside\t$bases_outside\t$median_outside\t$pct10_outside\t$pct200_outside" >> $RESULTS
    
done
